apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-01
spec:
  topology:
    controlPlane:
      count: 1
      class: guaranteed-small
      storageClass: tanzu-gold-storage-policy
    workers:
      count: 2
      class: guaranteed-small
      storageClass: tanzu-gold-storage-policy
  distribution:
    version: v1.21
